-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.bounties
(
    id serial NOT NULL,
    name text NOT NULL,
    bounty money NOT NULL,
    "createdAt" time without time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);
END;